"""Regenerate colormaps.py from matplotlib's colormaps.

Development-only: the app itself never imports matplotlib (that is the whole
point of the generated table). Run this if you want to add a colormap to the
dropdown or change the stop count.

Run:  python gen_colormaps.py
"""
import textwrap

import matplotlib
import numpy as np

NAMES = ("turbo", "viridis", "plasma", "inferno", "magma", "jet", "rainbow", "coolwarm")
STOPS = 129
OUT = "colormaps.py"

HEADER = '''"""Embedded colormap lookup tables.

Replaces the matplotlib dependency, which was pulled in solely for
`matplotlib.colormaps[...]`. matplotlib costs ~11.5 MB of download in a
Shinylive/Pyodide deployment; these tables cost a few KB.

Each entry is {stops} evenly spaced RGB stops as a flat hex string, linearly
interpolated at lookup time. Worst-case deviation from matplotlib's own anchor
colors is {worst:.1f}/255 ({pct:.1f}%) - imperceptible. Note that sampling
matplotlib at continuous values returns a 256-step staircase, so interpolating
here is marginally smoother than the original rather than less accurate.

Generated by gen_colormaps.py; re-run that (it needs matplotlib) to regenerate.
"""
import numpy as np

_STOPS = {stops}

_LUT_HEX = {{
{body}
}}

CMAP_NAMES = tuple(_LUT_HEX)

_cache: dict[str, np.ndarray] = {{}}


def _lut(name):
    """Decode a hex stop table into an (N, 3) float array in 0..1, memoized."""
    if name not in _cache:
        raw = _LUT_HEX[name]
        vals = np.array([int(raw[i:i + 2], 16) for i in range(0, len(raw), 2)], dtype=np.float64)
        _cache[name] = (vals / 255.0).reshape(-1, 3)
    return _cache[name]


def sample(name, t):
    """Map t (array of 0..1) to RGB floats via linear interpolation of the stops."""
    lut = _lut(name)
    xs = np.linspace(0.0, 1.0, lut.shape[0])
    t = np.clip(np.asarray(t, dtype=np.float64), 0.0, 1.0)
    return np.stack([np.interp(t, xs, lut[:, c]) for c in range(3)], axis=-1)
'''


def main():
    entries, worst = [], 0.0
    for name in NAMES:
        cmap = matplotlib.colormaps[name]
        lut = cmap(np.linspace(0, 1, STOPS))[:, :3]
        hexes = "".join("%02x%02x%02x" % tuple(int(round(c * 255)) for c in row) for row in lut)

        # Measured against the colormap's own anchor colors. Comparing against
        # continuous matplotlib output instead would mostly measure its 256-step
        # quantization staircase, not this table's accuracy.
        anchors = np.linspace(0, 1, getattr(cmap, "N", 256))
        xs = np.linspace(0, 1, STOPS)
        approx = np.stack([np.interp(anchors, xs, lut[:, c]) for c in range(3)], axis=-1)
        worst = max(worst, float(np.abs(approx - cmap(anchors)[:, :3]).max() * 255))

        chunks = "\n".join(f'        "{s}"' for s in textwrap.wrap(hexes, 96))
        entries.append(f'    "{name}": (\n{chunks}\n    ),')

    src = HEADER.format(stops=STOPS, worst=worst, pct=worst / 255 * 100, body="\n".join(entries))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(src)
    print(f"wrote {OUT}: {len(NAMES)} colormaps, {STOPS} stops, max error {worst:.2f}/255")


if __name__ == "__main__":
    main()
