"""Embedded colormap lookup tables.

Replaces the matplotlib dependency, which was pulled in solely for
`matplotlib.colormaps[...]`. matplotlib costs ~11.5 MB of download in a
Shinylive/Pyodide deployment; these tables cost a few KB.

Each entry is 129 evenly spaced RGB stops as a flat hex string, linearly
interpolated at lookup time. Worst-case deviation from matplotlib's own anchor
colors is 4.5/255 (1.8%) - imperceptible. Note that sampling
matplotlib at continuous values returns a 256-step staircase, so interpolating
here is marginally smoother than the original rather than less accurate.

Generated by gen_colormaps.py; re-run that (it needs matplotlib) to regenerate.
"""
import numpy as np

_STOPS = 129

_LUT_HEX = {
    "turbo": (
        "30123b33184a351e58372466392a733b2f803d358b3f3b974040a24146ac424bb54451bf4456c7455ccf4661d64666dd"
        "466be34771e94776ee477bf24680f64685fa458afc448ffe4294ff4099ff3d9efe3aa3fc37a8fa33adf72fb2f42cb7f0"
        "28bceb25c0e722c5e21fc9dd1ccdd81ad2d219d5cd18d9c818ddc218e0bd19e3b91ce6b41fe9af22ebaa27eea42cf09e"
        "32f29838f4913ff68a46f8844ef97d55fa765dfc6f65fd696dfe6275fe5c7dff5684ff518bff4b92ff4799fe429ffd3f"
        "a4fc3ca9fb39affa37b4f836b9f635bef434c3f134c8ef34cdec34d2e935d7e535dbe236dfdf37e3db38e7d739ebd339"
        "eecf3af1cb3af4c73af6c33af8be39faba39fbb637fcb136fdac34fea732fea130fe9b2dfe962bfe9029fd8a26fc8423"
        "fb7e21f9781ef8721cf66c19f46617f26014f05b12ed5510eb500ee84b0ce5470be2430adf3f08dc3b07d83706d43305"
        "d02f05cc2b04c82803c32503be2102b91e02b41b01af1801a91601a413019e1001980e01920b018b09028507027e0502"
        "7a0403"
    ),
    "viridis": (
        "44015445045746075a460a5d470d6047106347136548166848186a481b6d481d6f482071482374482576482878472a7a"
        "472d7b472f7d46327e463480453781443983443b84433e854240864142874045883f47883e49893e4c8a3d4e8a3c508b"
        "3b528b3a548c39568c38598c375b8d365d8d355f8d34618d33638d32658e31678e30698e2f6b8e2e6d8e2e6f8e2d718e"
        "2c728e2b748e2a768e2a788e297a8e287c8e277e8e27808e26828e25838e25858e24878e23898e228b8d228d8d218f8d"
        "21918c20928c1f948c1f968b1f988b1f9a8a1e9c891f9e891fa0881fa18720a38621a58522a78523a98325ab8226ad81"
        "28ae802ab07f2db27d2fb47c32b67a35b77938b9773bbb753fbc7342be7146c06f4ac16d4ec36b52c56956c6675ac864"
        "5ec96263cb5f67cc5c6ccd5a70cf5775d0547ad1517fd34e84d44b89d5488ed64593d74198d83e9dd93ba2da37a8db34"
        "addc30b2dd2db8de29bddf26c2df23c8e020cde11dd2e21bd8e219dde318e2e418e7e419ece51bf1e51df6e620fbe723"
        "fde725"
    ),
    "plasma": (
        "0d088713078919068c1d068e2206902605912a05932e059531059735049838049a3c049b3f049c43039e46039f4903a0"
        "4c02a15002a25302a35601a45901a55c01a66001a66300a76600a76900a86c00a86f00a87201a87501a87801a87b02a8"
        "7e03a88104a78405a78707a68a09a58d0ba58f0da4920fa39511a19814a09a169f9d189da01a9ca21d9aa51f99a72197"
        "aa2395ac2694ae2892b12a90b32c8eb52f8cb7318aba3388bc3587be3885c03a83c23c81c43e7fc6417dc8437bca457a"
        "cc4778cd4a76cf4c74d14e72d35171d5536fd6556dd8576bda5a6adb5c68dd5e66de6164e06363e26561e3685fe56a5d"
        "e66c5ce76f5ae97158ea7457eb7655ed7953ee7b51ef7e50f0804ef1834cf3854bf48849f58b47f68d45f79044f79342"
        "f89540f9983efa9b3dfa9e3bfba139fca338fca636fca934fdac33fdaf31fdb22ffdb52efeb82cfebb2bfebe2afdc229"
        "fdc527fdc827fdcb26fcce25fcd225fbd524fad824f9dc24f8df25f7e225f6e626f5e926f4ed27f3f027f1f426f0f724"
        "f0f921"
    ),
    "inferno": (
        "00000401010602010a02020e04031205041707051b09061f0b07240d082910092d120a32150b37180c3c1b0c411e0c45"
        "210c4a240c4f280b532b0b572f0a5b320a5e3609613909633d0965400a67440a68470b6a4a0c6b4d0d6c510e6c540f6d"
        "57106e5a116e5d126e61136e64156e67166e6a176e6d186e71196e741a6e771c6d7a1d6d7d1e6d801f6c84206b87216b"
        "8a226a8d23699025689326679727669a28659d2964a02a63a32c61a62d60a92e5ead305db0315bb3325ab63458b93556"
        "bc3754bf3952c13a50c43c4ec73e4cca404acc4248cf4446d24644d44842d74b3fd94d3ddb503bde5238e05536e25734"
        "e45a31e65d2fe8602dea632aeb6628ed6925ef6c23f06f20f1731df3761bf47918f57d15f68013f78410f8870ef98b0b"
        "f98e09fa9207fb9606fb9906fb9d07fca108fca50afca80dfcac11fcb014fcb418fbb81dfbbc21fac026fac42af9c72f"
        "f9cb35f8cf3af7d340f6d746f5db4cf4df53f3e35af2e661f2ea69f1ed71f1f179f2f482f3f68af5f992f8fb9afafda1"
        "fcffa4"
    ),
    "magma": (
        "00000401010602010902020d03031205041606051a08071e0a08220c09260e0b2b110c2f130d34150e38180f3d1a1042"
        "1d114720114b22115025125529115a2c115f2f116333106736106b390f6e3d0f71400f74440f764710784a10794e117b"
        "51127c54137d57157e5a167e5d177f601880641a80671b806a1c816d1d81701f817320817621817922827c2382802582"
        "8326818627818928818c2981902a81932b80962c80992d809c2e7fa02f7fa3307ea6317daa337dad347cb0357bb3367a"
        "b73779ba3878bd3977c03a76c43c75c73d73ca3e72cd4071d0416fd3436ed6456cd9466bdc4869df4a68e24d66e44f64"
        "e75263e95462eb5760ed5a5fef5d5ef1605df2645cf4675cf56b5cf66e5cf7725cf8765cf9795dfa7d5efa815ffb8560"
        "fc8961fc8c63fc9065fd9467fd9869fd9b6bfe9f6dfea36ffea772feaa74feae77feb27afeb67cfeb97ffebd82fec185"
        "fec488fec88cfecc8ffecf92fed395fed799fdda9cfddea0fde2a3fde5a7fde9aafcecaefcf0b2fcf4b6fcf7b9fcfbbd"
        "fcfdbf"
    ),
    "jet": (
        "00008000008900009200009b0000a40000ad0000b60000bf0000c80000d10000da0000e30000ed0000f60000ff0000ff"
        "0000ff0008ff0010ff0018ff0020ff0028ff0030ff0038ff0040ff0048ff0050ff0058ff0060ff0068ff0070ff0078ff"
        "0080ff0088ff0090ff0098ff00a0ff00a8ff00b0ff00b8ff00c0ff00c8ff00d0ff00d8ff00e0fb02e8f409f0ee0ff8e7"
        "16ffe11cffdb23ffd429ffce30ffc736ffc13cffba43ffb449ffad50ffa756ffa05dff9a63ff946aff8d70ff8777ff80"
        "7dff7a83ff738aff6d90ff6697ff609dff5aa4ff53aaff4db1ff46b7ff40beff39c4ff33caff2cd1ff26d7ff1fdeff19"
        "e4ff13ebff0cf1fc06f8f500feed00ffe600ffde00ffd700ffd000ffc800ffc100ffb900ffb200ffab00ffa300ff9c00"
        "ff9400ff8d00ff8600ff7e00ff7700ff6f00ff6800ff6000ff5900ff5200ff4a00ff4300ff3b00ff3400ff2d00ff2500"
        "ff1e00ff1600fa0f00f10800e80000df0000d60000cd0000c40000bb0000b20000a800009f00009600008d0000840000"
        "800000"
    ),
    "rainbow": (
        "8000ff7c06ff780dff7413ff7019ff6c1fff6826fe642cfe6032fe5c38fd583efd5444fd504afc4c50fc4856fb445cfb"
        "4062fa3c68f9386df93473f83079f72c7ef72884f62489f5208ef41c93f31898f2149df110a2f00ca7ef08acee04b0ed"
        "00b5eb04b9ea08bee90dc2e810c6e614cae518cde41dd1e220d5e124d8df28dbde2ddedc30e1da34e4d938e7d73dead5"
        "40ecd444eed248f1d04df3ce50f4cc54f6cb58f8c95df9c760fac564fbc368fcc16dfdbf70febc74feba78ffb87dffb6"
        "80ffb484ffb288ffaf8cfead90feab94fda899fca69cfba4a0faa1a4f89fa8f79cacf59ab0f397b4f295b9ef92bced8f"
        "c0eb8dc4e88ac8e688cce385d0e082d4dd80d9da7ddcd67ae0d377e4cf74e8cb72ecc86ff0c46cf4c069f9bb66fcb763"
        "ffb360ffae5effa95bffa558ffa055ff9b52ff964fff914cff8c49ff8646ff8143ff7b40ff763dff703aff6b37ff6533"
        "ff5f30ff592dff532aff4d27ff4724ff4121ff3b1eff351bff2f18ff2914ff2211ff1c0eff160bff1008ff0905ff0302"
        "ff0000"
    ),
    "coolwarm": (
        "3b4cc03d50c33f53c64257c9445acc465ecf4961d24b64d54e68d8506bda536edd5572df5875e15a78e45d7ce65f7fe8"
        "6282ea6485ec6788ee6a8bef6c8ff16f92f37295f47597f6779af77a9df87da0f980a3fa82a6fb85a8fc88abfd8badfd"
        "8db0fe90b2fe93b5fe96b7ff98b9ff9bbcff9ebeffa1c0ffa3c2fea6c4fea9c6fdabc8fdaec9fcb1cbfcb3cdfbb6cefa"
        "b9d0f9bbd1f8bed2f6c0d4f5c3d5f4c5d6f2c7d7f0cad8efccd9edcedaebd1dae9d3dbe7d5dbe5d7dce3d9dce1dbdcde"
        "dddcdcdfdbd9e1dad6e3d9d3e5d8d1e7d7cee9d5cbead4c8ecd3c5edd1c2efcfbff0cdbbf1ccb8f2cab5f3c8b2f4c6af"
        "f5c4acf5c1a9f6bfa6f6bda2f7ba9ff7b89cf7b599f7b396f7b093f7ad90f7aa8cf7a889f6a586f6a283f59f80f59c7d"
        "f4987af39577f29274f18f71f08b6eef886bee8468ec8165eb7d62e97a5fe8765ce67259e46e56e36b54e16751df634e"
        "dd5f4bda5a49d85646d65244d44e41d1493fcf453ccc403aca3b37c73635c43032c12b30be242ebb1b2cb8122ab50927"
        "b40426"
    ),
}

CMAP_NAMES = tuple(_LUT_HEX)

_cache: dict[str, np.ndarray] = {}


def _lut(name):
    """Decode a hex stop table into an (N, 3) float array in 0..1, memoized."""
    if name not in _cache:
        raw = _LUT_HEX[name]
        vals = np.array([int(raw[i:i + 2], 16) for i in range(0, len(raw), 2)], dtype=np.float64)
        _cache[name] = (vals / 255.0).reshape(-1, 3)
    return _cache[name]


def sample(name, t):
    """Map t (array of 0..1) to RGB floats via linear interpolation of the stops."""
    lut = _lut(name)
    xs = np.linspace(0.0, 1.0, lut.shape[0])
    t = np.clip(np.asarray(t, dtype=np.float64), 0.0, 1.0)
    return np.stack([np.interp(t, xs, lut[:, c]) for c in range(3)], axis=-1)
